FROM maven:latest as maven_builder
RUN mkdir -p /apache-tomcat-9.0.65/apache-tomcat-9.0.65/webapps
WORKDIR /webapps
COPY pom.xml /webapps
RUN mvn -B dependency:resolve dependency:resolve-plugins
COPY src /app/src
RUN mvn package

FROM tomcat

EXPOSE 8080
WORKDIR /webapps
COPY --from=maven_builder target/javarush_game-1.0-SNAPSHOT.war .javarush_game-1.0.war
